### ISSUE TITLE
Failed to create dimension

### ISSUE THREAD

**Issue by 77wisher77** [TheFloydman/More-Mystcraft#9]
often when trying to create a dimension errors like this appear. 

<details>
<summary>
Log
</summary>

```
[03:43:32] [Server thread/ERROR] [Mystcraft]: Attempting to generate age containing unmatched symbol moremystcraft:size_uncommon.  Results are undefined.
[03:43:32] [Server thread/ERROR] [Mystcraft]: Attempting to generate age containing unmatched symbol moremystcraft:size_common.  Results are undefined.
[03:43:32] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/lwjgl/util/vector/Vector3f
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/util/vector/Vector3f
	at thefloydman.moremystcraft.symbol.symbols.SymbolSunTinted$CelestialObject.getSunPos(SymbolSunTinted.java:336) ~[SymbolSunTinted$CelestialObject.class:?]
	at thefloydman.moremystcraft.symbol.symbols.SymbolSunTinted$CelestialObject.getAltitudeAngle(SymbolSunTinted.java:163) ~[SymbolSunTinted$CelestialObject.class:?]
	at com.xcompwiz.mystcraft.world.AgeController.calculateCelestialAngle(AgeController.java:660) ~[AgeController.class:?]
	at com.xcompwiz.mystcraft.world.WorldProviderMyst.calculateCelestialAngle(WorldProviderMyst.java:130) ~[WorldProviderMyst.class:?]
	at net.minecraft.world.World.getCelestialAngle(World.java:1537) ~[amu.class:?]
	at net.minecraft.world.World.getSunBrightnessFactor(World.java:1445) ~[amu.class:?]
	at net.minecraft.world.WorldProvider.getSunBrightnessFactor(WorldProvider.java:447) ~[aym.class:?]
	at net.minecraft.world.World.calculateSkylightSubtracted(World.java:1431) ~[amu.class:?]
	at net.minecraft.world.World.calculateInitialSkylight(World.java:2524) ~[amu.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:121) ~[oo.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:18) ~[ok.class:?]
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:263) ~[DimensionManager.class:?]
	at net.minecraft.server.MinecraftServer.getWorld(MinecraftServer.java:832) ~[MinecraftServer.class:?]
	at com.xcompwiz.mystcraft.linking.LinkController.travelEntity(LinkController.java:48) ~[LinkController.class:?]
	at com.xcompwiz.mystcraft.item.ItemLinking.activate(ItemLinking.java:89) ~[ItemLinking.class:?]
	at com.xcompwiz.mystcraft.item.ItemAgebook.activate(ItemAgebook.java:136) ~[ItemAgebook.class:?]
	at com.xcompwiz.mystcraft.tileentity.TileEntityBookRotateable.link(TileEntityBookRotateable.java:55) ~[TileEntityBookRotateable.class:?]
	at com.xcompwiz.mystcraft.inventory.ContainerBook.processMessage(ContainerBook.java:303) ~[ContainerBook.class:?]
	at com.xcompwiz.mystcraft.network.packet.MPacketGuiMessage.lambda$onMessage$0(MPacketGuiMessage.java:65) ~[MPacketGuiMessage.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
```

</details>

`moremystcraft:size_uncommon` I've seen that part of the message say a few other things like, rare

This is on version `R-1.1.0` of the Onion Sage Adventures pack
More Mystcraft version: `0.4.3`
Mystcraft Version: `0.13.7.02`

**Comment by TheFloydman** [comment]
Does it cause a crash? And is it a server or client?

**Comment by TheFloydman** [comment]
(As for the bits about moremystcraft:size, my tinted suns accept a size page, and there the rare, uncommon, etc. are different paths used to generate a random size when one is not specified. Since you have disabled size pages, the error is given. The tinted suns default to a medium size if none can be generated.)

**Comment by 77wisher77** [comment]
ahh, yes i disabled those as i wanted biomes to work as normal, I prefer the tiny/medium pages etc. However i wanted the additional types you added still : P

different sized suns isn't necessary so i will probably live with that continuing being disabled

**Comment by 77wisher77** [comment]
Thankyou for the fix though!
